### PR TITLE
Fixes broken logic for showing variant title on cart item view

### PR DESCRIPTION
**Pull request by sleroux**

### CODE REVIEW

**Comment by JakeCataford** [comment]
Should it use `String.IsNullOrEmpty`?

**Comment by sleroux** [comment]
Didn't know that was a thing! I'll update it

**Comment by JakeCataford** [comment]
did the tests pass on that? I think it might be lowercase `string` lol

**Comment by JakeCataford** [comment]
nvm im wrong its upcase

**Pull request merged**
