### PR TITLE
Part 1 - Fix layout and add click handling for multi product list view (Now with 100% more loading animation!)

### PR DESCRIPTION
**Pull request by sleroux**
Figured I would split this stuff into parts to get it landed quicker.

This fixes errors that were happening on the product list view because of missing component references, adds clickable product list items, and fixes up the busted commit for badge animations. The list view no longer scrolls because of the click handling but I'll fix that up in a follow up.

### CODE REVIEW

**Comment by sleroux** [comment]
I also added in the loading animation for the list view as part of this PR.

**Comment by JakeCataford** [comment]
unity_2017_1_3f1_personal__64bit__-_testing_scene_unity_-_unity-buy-sdk_-_pc__mac___linux_standalone__personal___opengl_4_1_

Noticing some weirdness on my end? dunno why just yet

**Comment by sleroux** [comment]
Sorry about that. Fixed the alignment issue!

**Comment by JakeCataford** [comment]
@sleroux Rebased and fixed the conflict on this, looking good now!

**Pull request merged**
